# Generated by Django 4.2.3 on 2023-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='register_patient',
            options={'ordering': ['First_Name']},
        ),
        migrations.AddField(
            model_name='register_patient',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
