# Generated by Django 4.2.3 on 2023-07-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_nurse_alter_register_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_patient',
            options={'ordering': ['Created_at']},
        ),
    ]
