# Generated by Django 4.2.3 on 2023-07-23 20:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_register_patient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Room', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='register_patient',
            options={'ordering': ['Created_at']},
        ),
        migrations.AddField(
            model_name='nurse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient.register_patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='status',
            field=models.CharField( max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='doctor',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='patient.doctors'),
            preserve_default=False,
        ),
    ]
