# Generated by Django 4.2.3 on 2023-07-24 12:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_doctors_alter_register_patient_options_nurse_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register_patient',
            managers=[
                ('Birth_Day', django.db.models.manager.Manager()),
            ],
        ),
    ]
