# Generated by Django 4.2.3 on 2023-07-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_register_patient_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='status',
            field=models.TextField(max_length=700),
        ),
    ]
