# Generated by Django 4.2.3 on 2023-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_nurse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_patient',
            name='is_Active_For_Nurse',
            field=models.BooleanField(default=True),
        ),
    ]
